version: '3.8'

services:
  # Frontend service (development)
  frontend-dev:
    build:
      context: ./ChatGptUi
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./ChatGptUi:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - chatgpt-network

  # API service (development)
  api-dev:
    build:
      context: ./OpenAiApi
      dockerfile: Dockerfile.dev
    ports:
      - "5221:5221"
    volumes:
      - ./OpenAiApi:/src
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5221
      - OpenAI__ApiKey=${OPENAI_API_KEY}
    networks:
      - chatgpt-network

networks:
  chatgpt-network:
    driver: bridge 